### ISSUE TITLE
Peechy

### ISSUE THREAD

**Issue by Optogram** [sqfmi/watchy-cases#1]
Hello,

Name : Peechy
Licence : Do whathever you want
List of files : Top, Bottom and Button

Here is **Peechy**, a cross design between _Pebble_ and _Watchy_.

STL Files : ( Can't upload STL directly )  [Peechy-STL.zip](https://github.com/sqfmi/watchy-cases/files/5939109/Peechy-STL.zip)

I'm not an expert in 3D or technical design, the files are not as clean as the reference design, I tried to submit a design that would fullfil my wishes about the watch.

What I love about Watchy, is the blunt design, I really likes the fact that you can see the components directly on your wrist, making the form being the function.
I appreciate a bit of comfort too, so I tried to mix the Watchy reference case, with the entire screen board visible and buttons a bit more integrated than the reference design.

Here is some **pictures** ! 

![Camera 01](https://user-images.githubusercontent.com/78688254/107148485-9ea8d980-6953-11eb-893b-6cca46d2f8be.jpg)
![Camera 02](https://user-images.githubusercontent.com/78688254/107148486-a10b3380-6953-11eb-8f70-28a0f92f3a3a.jpg)
![Camera 03](https://user-images.githubusercontent.com/78688254/107148487-a2d4f700-6953-11eb-8a4c-344f6db9defc.jpg)

Don't forget the metal 👍 
![Camera 01_Metal](https://user-images.githubusercontent.com/78688254/107148497-b4b69a00-6953-11eb-83e1-81fef365053f.jpg)

Have a great day !

**Comment by sqfmi** [comment]
@optogram beautiful renders!

**Comment by sqfmi** [comment]
@Optogram added to main repo and submitted your design for our contest!

**Comment by sqfmi** [comment]
Closing

**Comment by sqfmi** [comment]
@Optogram  congratulations on winning third place for the design contest! Please reach out to us via woo@sqfmi.com or DM us on Twitter with your contact info so you can collect your prize!
