### ISSUE TITLE
Tech Case

### ISSUE THREAD

**Issue by cyc-x** [sqfmi/watchy-cases#2]
Name : Tech Case
License : Open/MIT
List of files : Top.stl, Bottom.stl, Button.stl (4)

Here is my attempt at a case for Watchy. I wanted it to look more techincal/geometric and not bulky. The use of the existing strap holes hopefully makes it more minimal and sleeker as well, while still offering some protection.

It may need small updates for it to actually work, due to clearances/etc. (I don't yet have the watchy or a 3D printer.)

Attached are also some quick renders. If anyone wants to submit some better renders, that would be great!

Thanks!

[README.txt](https://github.com/sqfmi/watchy-cases/files/6086951/README.txt)
[TechCase.zip](https://github.com/sqfmi/watchy-cases/files/6086948/TechCase.zip)
![TechCase1](https://user-images.githubusercontent.com/80069240/110038895-41efd300-7cf5-11eb-985e-09d9a3635cd3.jpg)
![TechCase2](https://user-images.githubusercontent.com/80069240/110038902-44522d00-7cf5-11eb-9194-f948b300a8de.jpg)
![TechCase3](https://user-images.githubusercontent.com/80069240/110038907-474d1d80-7cf5-11eb-99c2-a292d3be4daa.jpg)
![TechCase4](https://user-images.githubusercontent.com/80069240/110038909-4916e100-7cf5-11eb-80e7-1da54ac37a98.jpg)

**Comment by sqfmi** [comment]
@cyc-x looks sleek!

**Comment by sqfmi** [comment]
@cyc-x added https://github.com/sqfmi/watchy-cases/tree/main/Tech_Case
