### ISSUE TITLE
Slim

### ISSUE THREAD

**Issue by BraininaBowl** [sqfmi/watchy-cases#3]
**Introducing Slim: the minimal case for Watchy.**
[https://github.com/BraininaBowl/Slim---A-case-for-Watchy](https://github.com/BraininaBowl/Slim---A-case-for-Watchy)

A watch case carefully designed to add as little bulk as possible. You'll need the front, the back and four buttons. Installation: But the back down on its back. Slip the four buttons in, lower your Watchy into it and put the face plate on top of it all. Just thread your strap through the hoops and you're ready to go.

Files: 
**Slim V4.5.3 - back.stl
Slim V4.5.3 - button.stl
Slim V4.5.3 - front.stl**

Licence: 
**MIT**

Author: 
**Frans van Bellen/Brain in a Bowl**

![render2](https://user-images.githubusercontent.com/18479678/110258387-a97e7a80-7fa2-11eb-9129-bb96a5b6a3f2.png)

**Comment by sqfmi** [comment]
Awesome, thanks for the entry @BraininaBowl!

**Comment by BraininaBowl** [comment]
Updated with a slightly smoother back and actual buttons.

**Comment by sqfmi** [comment]
@BraininaBowl added to main repo https://github.com/sqfmi/watchy-cases/tree/main/Slim
